**WRITER'S IDENTITY**
- AZIMIL GANI ALAM
- Ph.D Student
- Dept. Energy & Process Tech - NTNU


**NOTE :**
- This Python File runs in GoogleColab
- This work uses **Room Sensors Data Record by Building Management System**
- we want to filterize data results from CSV models become process-ready for Machine Learning process

**RULES**
1. Run Library Import
2. Select Notebook platform by run one of those commands.
3. Expand Schools Tab
 - Run Identity and Data Caller
 - Expand Classrooms
 - Run one of Klasserom- XXX
 - Run Processor. if done, select again one of Klasserom and run again the processor. it is cyclic process

to check the data cleaning result, run 'Data Preparation'.

# Libraries Import

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from datetime import datetime, timedelta
import pytz

# Default Names & Setting

In [2]:
school_col_name   = 'school_id'
room_col_name     = 'room_id'
date_name         = 'date'
time_name         = 'time'
manuf_col_name    = 'manuf_id'
instr_col_name    = 'instr_id'
serial_col_name   = 'serial_id'
temp_set_name     = 'temp_s'
temp_data_name    = 'temp_v'
temp_floor_name   = 'temp_f'
co2_data_name    = 'co2_v'
switch_floor_col_name = 'swc_f'
switch_room_col_name  =  'swc_r'

vent_data_name = 'vent_v'
temp_data_name = 'temp_v'

#identify a datetime name : wont be displayed. just coding purpose
datetime_name = 'datetime'

In [3]:
#filtering rows data regarding to desired specific time
start_time = '00:00:00'
end_time = '23:59:59'
start_date = '2023-02-06'
end_date  =  '2023-05-30'
spec_date = pd.to_datetime('today').strftime("%Y-%m-%d")
name_date = pd.to_datetime('today').strftime("%y%m%d")
date_format_show =  '%Y-%m-%d'
time_format_show =  '%H:%M'

# Define the timezones (UTC and Europe/Oslo)
utc_timezone = pytz.timezone('UTC')
oslo_timezone = pytz.timezone('Europe/Oslo')

#Folder naming directory
platform_directory = 'C:/Users/azimilga'
folder_raw = 'data-raw'
folder_ready = 'data-ready'
folder_year = '2023'
folder_project = 'project'

# Bratteberg

## Identity

In [4]:
school_name = 'bratteberg'
manuf_id    = 'sdanlegg'
input_file_directory    = platform_directory + '/' + folder_project + '/' + folder_raw  + '/' + folder_year + '/' + school_name + '/' + manuf_id + '/'
export_file_directory   = platform_directory + '/'+ folder_project + '/' + folder_ready + '/' + folder_year + '/' + school_name + '/' + manuf_id + '/'

## Data Caller

In [5]:
folder_path1 = input_file_directory # replace with the folder path
csv_files1 = [f for f in os.listdir(folder_path1) if f.endswith('.csv')] # get list of csv files

dfs1 = [] # list to store dataframes

for file in csv_files1:
    file_path = os.path.join(folder_path1, file) # get full path of csv file
    df = pd.read_csv(file_path, delimiter = ';').iloc[3:] # read csv file into a dataframe
    dfs1.append(df) # append dataframe to list

## Classrooms

### Klasserom 141

In [6]:
class_dir = '141'
instr_id = 'sauter'
serial_id = 'noserial'
file_name = serial_id+'-latest.csv'

columns_change   = { '+BRASKUL=564.001-LH6141'    : switch_room_col_name,
                     '+BRASKUL=564.001-LH6141G'    : switch_floor_col_name,
                     '+BRASKUL=564.001-RT6141'    : temp_data_name,
                     '+BRASKUL=564.001-RT6141G'   : temp_floor_name,
                     '+BRASKUL=564.001-RT6141spA' : temp_set_name }
columns_arrangement = school_col_name , room_col_name, date_name, time_name, manuf_col_name, instr_col_name, serial_col_name  , switch_floor_col_name, switch_room_col_name, temp_data_name, temp_floor_name, temp_set_name

### Klasserom 142

In [14]:
class_dir = '142'
instr_id = 'spaceplus'
serial_id = '2930144209'
file_name = serial_id+'-latest.csv'

columns_change   = { '+BRASKUL=564.001-LH6142'    : switch_room_col_name,
                     '+BRASKUL=564.001-LH6142G'   : switch_floor_col_name,
                     '+BRASKUL=564.001-RT6142'    : temp_data_name,
                     '+BRASKUL=564.001-RT6142G'   : temp_floor_name,
                     '+BRASKUL=564.001-RT6142spA' : temp_set_name }
columns_arrangement = school_col_name , room_col_name, date_name, time_name, manuf_col_name, instr_col_name, serial_col_name  , switch_floor_col_name, switch_room_col_name, temp_data_name, temp_floor_name, temp_set_name

### Klasserom 210

In [23]:
room_id = 210
class_dir = '210'
instr_id = 'spaceplus'
serial_id = '2930157154'
file_name = serial_id+'-latest.csv'

columns_change   = { '+BRASKUL=564.001-LZ6210'    : switch_room_col_name,
                     '+BRASKUL=564.001-RT6210'    : temp_data_name,
                     '+BRASKUL=564.001-RT6210spA' : temp_set_name }
columns_arrangement = school_col_name , room_col_name, date_name, time_name, manuf_col_name, instr_col_name, serial_col_name  , switch_room_col_name, temp_data_name, temp_set_name

## Processor

In [7]:
# concatenate dataframes in the list into a single dataframe
DF1 = pd.concat(dfs1, ignore_index=False) #.fillna(method='backfill')
DF1['Name :'] = pd.to_datetime(DF1['Name :'], utc=False)
DF1.sort_values (by='Name :', inplace=True)
#DF1.set_index('Name :', inplace=True)

# Adjust the datetime to the Oslo timezone and account for daylight saving time
#DF1['Name :'] = DF1['Name :'].dt.tz_convert(utc_timezone)
DF1['Name :'] = DF1['Name :'].dt.tz_localize(oslo_timezone, nonexistent='raise').dt.tz_convert(utc_timezone)
DF1['Name :'] = DF1['Name :'].dt.tz_localize(None)
DF1[date_name]   = DF1['Name :'].dt.strftime(date_format_show)
DF1[time_name]   = DF1['Name :'].dt.strftime(time_format_show)
DF1.drop(columns=['Name :'], inplace = True)

DF1 [school_col_name]  = school_name
DF1 [room_col_name]    = class_dir
DF1 [manuf_col_name]   = manuf_id
DF1 [instr_col_name]   = instr_id
DF1 [serial_col_name]  = serial_id
data_index = DF1.iloc[:,13:]
measured_data = DF1.iloc[:,:13] #.astype(float).interpolate(method='linear').fillna(method='bfill')
DF1 = pd.concat([data_index,measured_data],axis=1)
DF1.rename(columns= columns_change, inplace=True)
DF1 = DF1.loc[:,columns_arrangement].dropna(how='any')

In [10]:
DF1 #.head(8)

,school_id,room_id,date,time,manuf_id,instr_id,serial_id,swc_f,swc_r,temp_v,temp_f,temp_s
4,bratteberg,141,2023-03-07,23:00,sdanlegg,sauter,noserial,1.00,1.00,19.4,21.8,21.0
6,bratteberg,141,2023-03-07,23:01,sdanlegg,sauter,noserial,1.00,1.00,19.4,21.8,21.0
8,bratteberg,141,2023-03-07,23:02,sdanlegg,sauter,noserial,1.00,1.00,19.4,21.8,21.0
10,bratteberg,141,2023-03-07,23:03,sdanlegg,sauter,noserial,1.00,1.00,19.6,21.8,21.0
12,bratteberg,141,2023-03-07,23:04,sdanlegg,sauter,noserial,1.00,1.00,19.4,22.1,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1438,bratteberg,141,2023-04-23,21:55,sdanlegg,sauter,noserial,0.00,1.00,19.6,20.0,21.0
1439,bratteberg,141,2023-04-23,21:56,sdanlegg,sauter,noserial,0.00,1.00,19.6,20.0,21.0
1440,bratteberg,141,2023-04-23,21:57,sdanlegg,sauter,noserial,0.00,1.00,19.6,20.0,21.0
1441,bratteberg,141,2023-04-23,21:58,sdanlegg,sauter,noserial,0.00,1.00,19.6,20.0,21.0
1442,bratteberg,141,2023-04-23,21:59,sdanlegg,sauter,noserial,0.00,1.00,19.6,20.0,21.0

In [25]:
#put spesific Directory and File Name.
directory_path = export_file_directory+class_dir+'/'
name_time = datetime.strptime((DF1['time'].iloc[0]),'%H:%M').strftime('%H%M')
name_date = datetime.strptime((DF1['date'].iloc[0]),'%Y-%m-%d').strftime('%Y%m%d')

filename = school_name+'_'+class_dir+ '_'+ instr_id + '_'+serial_id +'_'+name_date +'_'+ name_time + '.csv'

# save dataframe to CSV file in specified directory
DF1.to_csv(directory_path + filename, index=False)

# Øyra

## Identity

In [26]:
#identify location and object name
school_name = 'øyra'
manuf_id    = 'sdanlegg'


#identify the origin file directories and destination file directory
input_file_directory_temp  = platform_directory + '/' + folder_project + '/' + folder_raw + '/' + folder_year + '/' + school_name + '/' + manuf_id + '_temp/'
input_file_directory_airfl = platform_directory + '/' + folder_project + '/' + folder_raw + '/' + folder_year + '/' + school_name + '/' + manuf_id + '_airfl/'
export_file_directory      = platform_directory + '/'+ folder_project + '/' + folder_ready + '/' + folder_year + '/' + school_name + '/' + manuf_id + '/'

## Data Caller

In [27]:
csv_files_temp = [f for f in os.listdir(input_file_directory_temp) if f.endswith('.csv')] # get list of csv files for SD anlegg data - temperature
dfa_temp       = [] # list to store dataframes
for file in csv_files_temp:
    file_path = os.path.join(input_file_directory_temp, file) # get full path of csv file
    dfx = pd.read_csv(file_path, delimiter = ';').iloc[3:]  # read csv file into a dataframe
    dfa_temp.append(dfx) # append dataframe to list

csv_files_airfl= [f for f in os.listdir(input_file_directory_airfl) if f.endswith('.csv')] # get list of csv files for SD anlegg data - airflow
dfa_airfl      = [] # list to store dataframes
for file in csv_files_airfl:
    file_path = os.path.join(input_file_directory_airfl, file) # get full path of csv file
    dfx = pd.read_csv(file_path, delimiter = ';') # read csv file into a dataframe
    dfa_airfl.append(dfx) # append dataframe to list

In [28]:
# concatenate dataframes in the list into a single dataframe
DF_temp  = pd.concat(dfa_temp, ignore_index=False) #.fillna(method='backfill')

#setpoint temperature is missing. we assumed the temperature is not far away than others setpoint temperature. check again to building owner
DF_temp['501353 563-RT307xs'] = ((((DF_temp['501353 563-RT307a'].astype(float) + DF_temp['501353 563-RT609a'].astype(float)) / 2).round(2)
))

datechange = pd.to_datetime(DF_temp['Name :'])

DF_temp[datetime_name] = datechange.dt.strftime(date_format_show + ' ' + time_format_show)

DF_temp = DF_temp.sort_values(['Name :'], ascending=True).fillna(method='ffill').reset_index(drop=True)
DF_temp = DF_temp.drop(columns=['Name :'], axis=1)
DF_temp['NØSK=563-RT400s'].fillna(method= 'backfill', inplace=True)

#convert the format, from object/string , become numbers (Float64)
DF_temp.iloc[:,:6] = (DF_temp.iloc[:,0:6].astype(float))

<ipython-input-28-0688156c37d2>:17: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  DF_temp.iloc[:,:6] = (DF_temp.iloc[:,0:6].astype(float))

In [29]:
DF_airfl = pd.concat(dfa_airfl, ignore_index=False) #.fillna(method='backfill')

#lets we divide the column 'recorded' which containing data about date and time in same cells. we make new columns : Date and Time.
datechange = pd.to_datetime(DF_airfl['Tidsstempel'])
DF_airfl[datetime_name] = datechange.dt.strftime('%Y-%m-%d %H:%M')
#we set column 'timestep' become the index and we sort it
DF_airfl = DF_airfl.sort_values(by=[datetime_name], ascending=True).reset_index(drop=True)
DF_airfl = DF_airfl.drop(columns=['Tidsstempel'], axis=1)

In [30]:
#join dataset about temperature and dataset about ventilation rate. and all values will be convert to Float64
DF_all = DF_temp.set_index(datetime_name).join(DF_airfl.set_index(datetime_name)).astype(float).interpolate(method= 'linear')

## Classrooms

### Klasserom 302

In [31]:
room_id = 302
class_dir = '302'
instr_id = 'sauter'
serial_id = 'noserial'
file_name = serial_id+'-latest.csv'
columns_to_call = { '501353 563-RT609a': temp_data_name ,
                    '501353 563-RT609s' : temp_set_name ,
                    '501353 360.06-SQ302TL (m³/h)' : vent_data_name }
columns_arrangement = [school_col_name, room_col_name, date_name, time_name, manuf_col_name, instr_col_name, serial_col_name  , temp_set_name, vent_data_name , temp_data_name ]

### Klasserom 303

In [41]:
room_id = 303
class_dir = '303'
instr_id = 'sauter'
serial_id = 'noserial'
file_name = serial_id+'-latest.csv'
columns_to_call = { 'NØSK=563-RT400a': temp_data_name ,
                    'NØSK=563-RT400s' : temp_set_name ,
                    'NØSK=360.04-SQ303TL (m³/h)' : vent_data_name }
columns_arrangement = [school_col_name, room_col_name, date_name, time_name, manuf_col_name, instr_col_name, serial_col_name  , temp_set_name, vent_data_name , temp_data_name ]

### Klasserom 339

In [51]:
room_id = 339
class_dir = '339'
instr_id = 'sauter'
serial_id = 'noserial'
file_name = serial_id+'-latest.csv'
columns_to_call = { '501353 563-RT307a': temp_data_name ,
                    '501353 563-RT307xs' : temp_set_name ,
                    '501353 360.03-SQ339TL (m³/h)' : vent_data_name }
columns_arrangement = [school_col_name, room_col_name, date_name, time_name, manuf_col_name, instr_col_name, serial_col_name  , temp_set_name, vent_data_name , temp_data_name ]

## Processor

In [52]:
DF2 = DF_all.reset_index()
#we move columns named 'Date' and 'Time' to the front side
DF2[datetime_name] = pd.to_datetime(DF2[datetime_name])

# Adjust the datetime to the Oslo timezone and account for daylight saving time
DF2[datetime_name] = DF2[datetime_name].dt.tz_localize(oslo_timezone, nonexistent='raise').dt.tz_convert(utc_timezone)
DF2[datetime_name] = DF2[datetime_name].dt.tz_localize(None)

datechange = DF2[datetime_name]
DF2[date_name] = datechange.dt.strftime('%Y-%m-%d')
DF2[time_name] = datechange.dt.strftime('%H:%M')

DF2 [school_col_name] = school_name
DF2 [room_col_name] = class_dir
DF2 [manuf_col_name] = manuf_id
DF2 [instr_col_name] = instr_id
DF2 [serial_col_name] = serial_id

DF2.rename(columns= columns_to_call, inplace=True)
DF2 = DF2.loc[:,columns_arrangement]
#DF2 = DF2[DF2['date']==spec_date]
#name_time =DF2['time'].iloc[0]

In [53]:
#put spesific Directory and File Name.
directory_path = export_file_directory+class_dir+'/'
name_time = datetime.strptime((DF2['time'].iloc[0]),'%H:%M').strftime('%H%M')
name_date = datetime.strptime((DF2['date'].iloc[0]),'%Y-%m-%d').strftime('%Y%m%d')

filename = school_name+'_'+class_dir+ '_'+ instr_id + '_'+serial_id +'_'+name_date +'_'+ name_time + '.csv'

# save dataframe to CSV file in specified directory
DF2.to_csv(directory_path + filename, index=False)

### Data preparation of Data Caller

In [54]:
def description(data_check):
    summary = pd.DataFrame(data_check.dtypes,columns=['dtypes']) #get the type
    summary['Miss-Null'] = data_check.isnull().sum().values #the count of missing value
    summary['Miss-NaN'] = data_check.isna().sum().values #the count of missing value
    summary['Uniques'] = data_check.nunique().values #the count of non-unique value
    summary['min value'] = data_check.min()
    summary['max value'] = data_check.max()
    summary['mean Value'] = data_check.mean()
    summary['rows of data'] = data_check.count()
    return summary;

description(DF_temp)

<ipython-input-54-06d82b816c96>:8: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  summary['mean Value'] = data_check.mean()

,dtypes,Miss-Null,Miss-NaN,Uniques,min value,max value,mean Value,rows of data
501353 563-RT307a,float64,0,0,24,21.4,23.7,22.072353,59796
501353 563-RT307xs,float64,0,0,39,21.15,23.05,21.679388,59796
501353 563-RT609a,float64,0,0,21,20.8,22.8,21.286427,59796
501353 563-RT609s,float64,0,0,1,21.0,21.0,21.000000,59796
NØSK=563-RT400a,float64,0,0,14,21.4,22.7,21.684372,59796
NØSK=563-RT400s,float64,0,0,1,21.6,21.6,21.600000,59796
datetime,object,0,0,59793,2023-03-08 00:06,2023-04-23 23:59,NaN,59796

In [55]:
def description(data_check):
    summary = pd.DataFrame(data_check.dtypes,columns=['dtypes']) #get the type
    summary['Miss-Null'] = data_check.isnull().sum().values #the count of missing value
    summary['Miss-NaN'] = data_check.isna().sum().values #the count of missing value
    summary['Uniques'] = data_check.nunique().values #the count of non-unique value
    summary['min value'] = data_check.min()
    summary['max value'] = data_check.max()
    summary['mean Value'] = data_check.mean()
    summary['rows of data'] = data_check.count()
    return summary;

description(DF_airfl)

<ipython-input-55-99563e8f1e96>:8: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  summary['mean Value'] = data_check.mean()

,dtypes,Miss-Null,Miss-NaN,Uniques,min value,max value,mean Value,rows of data
501353 360.03-SQ339TL (m³/h),float64,396,396,83,0.0,1363.0,1198.967360,7261
501353 360.06-SQ302TL (m³/h),float64,396,396,261,440.0,1374.0,1054.043245,7261
NØSK=360.04-SQ303TL (m³/h),float64,396,396,277,0.0,1353.0,880.454483,7261
datetime,object,0,0,7261,2023-03-08 00:06,2023-04-27 10:26,NaN,7657

In [56]:
def description(data_check):
    summary = pd.DataFrame(data_check.dtypes,columns=['dtypes']) #get the type
    summary['Miss-Null'] = data_check.isnull().sum().values #the count of missing value
    summary['Miss-NaN'] = data_check.isna().sum().values #the count of missing value
    summary['Uniques'] = data_check.nunique().values #the count of non-unique value
    summary['min value'] = data_check.min()
    summary['max value'] = data_check.max()
    summary['mean Value'] = data_check.mean()
    summary['rows of data'] = data_check.count()
    return summary;

description(DF_all)

,dtypes,Miss-Null,Miss-NaN,Uniques,min value,max value,mean Value,rows of data
501353 563-RT307a,float64,0,0,24,21.40,23.70,22.072324,60124
501353 563-RT307xs,float64,0,0,39,21.15,23.05,21.679483,60124
501353 563-RT609a,float64,0,0,21,20.80,22.80,21.286646,60124
501353 563-RT609s,float64,0,0,1,21.00,21.00,21.000000,60124
NØSK=563-RT400a,float64,0,0,14,21.40,22.70,21.684467,60124
NØSK=563-RT400s,float64,0,0,1,21.60,21.60,21.600000,60124
501353 360.03-SQ339TL (m³/h),float64,0,0,1755,0.00,1363.00,1198.921254,60124
501353 360.06-SQ302TL (m³/h),float64,0,0,7061,440.00,1374.00,1041.582779,60124
NØSK=360.04-SQ303TL (m³/h),float64,0,0,9102,0.00,1353.00,862.077931,60124

In [57]:
#we will join dataset about temperature and dataset about ventilation rate. any blank cell will be filled in with 'ffill' method, and all values will be convert to Float64
DF_check1 = DF_airfl.set_index('datetime').join(DF_temp.set_index('datetime')).astype(float).reset_index()

datechange = pd.to_datetime(DF_check1['datetime'])
DF_check1['date'] = datechange.dt.strftime('%Y-%m-%d')
 #.fillna(method='ffill')
print('data available date :')
print(DF_check1['date'].unique())
print('number of rows :', DF_check1['date'].count())

data available date :
['2023-03-08' '2023-03-09' '2023-03-10' '2023-03-11' '2023-03-12'
 '2023-03-13' '2023-03-14' '2023-03-15' '2023-03-16' '2023-03-17'
 '2023-03-18' '2023-03-19' '2023-03-20' '2023-03-21' '2023-03-22'
 '2023-03-23' '2023-03-24' '2023-03-25' '2023-03-26' '2023-03-27'
 '2023-03-28' '2023-03-29' '2023-03-30' '2023-03-31' '2023-04-01'
 '2023-04-02' '2023-04-03' '2023-04-04' '2023-04-05' '2023-04-06'
 '2023-04-07' '2023-04-08' '2023-04-09' '2023-04-10' '2023-04-11'
 '2023-04-12' '2023-04-13' '2023-04-14' '2023-04-15' '2023-04-16'
 '2023-04-17' '2023-04-18' '2023-04-19' '2023-04-20' '2023-04-21'
 '2023-04-22' '2023-04-23' '2023-04-24' '2023-04-25' '2023-04-26'
 '2023-04-27']
number of rows : 7660

In [58]:
#we will join dataset about temperature and dataset about ventilation rate. any blank cell will be filled in with 'ffill' method, and all values will be convert to Float64
DF_check2 = DF_temp.set_index('datetime').join(DF_airfl.set_index('datetime')).astype(float).reset_index()

datechange = pd.to_datetime(DF_check2['datetime'])
DF_check2['date'] = datechange.dt.strftime('%Y-%m-%d')
 #.fillna(method='ffill')
print('data available date :')
print(DF_check2['date'].unique())
print('number of rows :', DF_check2['date'].count())

data available date :
['2023-03-08' '2023-03-09' '2023-03-10' '2023-03-11' '2023-03-12'
 '2023-03-13' '2023-03-14' '2023-03-15' '2023-03-16' '2023-03-17'
 '2023-03-18' '2023-03-19' '2023-03-20' '2023-03-21' '2023-03-22'
 '2023-03-23' '2023-03-24' '2023-03-25' '2023-03-26' '2023-03-27'
 '2023-03-28' '2023-03-29' '2023-03-30' '2023-03-31' '2023-04-01'
 '2023-04-02' '2023-04-03' '2023-04-04' '2023-04-05' '2023-04-06'
 '2023-04-07' '2023-04-08' '2023-04-09' '2023-04-10' '2023-04-11'
 '2023-04-12' '2023-04-18' '2023-04-19' '2023-04-20' '2023-04-21'
 '2023-04-22' '2023-04-23']
number of rows : 60124

In [59]:
DF_check2

,datetime,501353 563-RT307a,501353 563-RT307xs,501353 563-RT609a,501353 563-RT609s,NØSK=563-RT400a,NØSK=563-RT400s,501353 360.03-SQ339TL (m³/h),501353 360.06-SQ302TL (m³/h),NØSK=360.04-SQ303TL (m³/h),date
0,2023-03-08 00:06,22.0,21.45,20.9,21.0,21.6,21.6,1178.0,497.0,413.0,2023-03-08
1,2023-03-08 00:16,22.0,21.45,20.9,21.0,21.6,21.6,1218.0,491.0,383.0,2023-03-08
2,2023-03-08 00:26,22.0,21.45,20.9,21.0,21.7,21.6,1208.0,502.0,398.0,2023-03-08
3,2023-03-08 00:36,21.9,21.50,21.1,21.0,21.7,21.6,1191.0,497.0,574.0,2023-03-08
4,2023-03-08 00:46,22.0,21.60,21.2,21.0,21.7,21.6,1191.0,502.0,1265.0,2023-03-08
...,...,...,...,...,...,...,...,...,...,...,...
60119,2023-04-23 23:55,22.0,21.55,21.1,21.0,21.7,21.6,NaN,NaN,NaN,2023-04-23
60120,2023-04-23 23:56,22.0,21.60,21.2,21.0,21.7,21.6,NaN,NaN,NaN,2023-04-23
60121,2023-04-23 23:57,21.9,21.55,21.2,21.0,21.6,21.6,NaN,NaN,NaN,2023-04-23
60122,2023-04-23 23:58,21.9,21.55,21.2,21.0,21.6,21.6,NaN,NaN,NaN,2023-04-23
60123,2023-04-23 23:59,21.9,21.55,21.2,21.0,21.6,21.6,NaN,NaN,NaN,2023-04-23

In [60]:
(DF_check2[DF_check2.isna().any(axis=1)])['date'].unique()
print('missing date : ')
print('August : 13,14,15,16,17,24,25,26,27')

missing date :
August : 13,14,15,16,17,24,25,26,27

# Brannfjell

## 23

In [61]:
school_name = 'brannfjell'
manuf_id    = 'sdanlegg'
instr_id    = 'schneider'
class_dir = '23'
serial_id = 'noserial'
input_file_directory  = platform_directory + '/' + folder_project + '/' + folder_raw   + '/' + folder_year + '/' + school_name + '/' + manuf_id + '/'+ class_dir + '/'
export_file_directory = platform_directory + '/' + folder_project + '/' + folder_ready + '/' + folder_year + '/' + school_name + '/' + manuf_id + '/'+ class_dir + '/'

## 27

In [66]:
school_name = 'brannfjell'
manuf_id    = 'sdanlegg'
instr_id    = 'schneider'
class_dir = '27'
serial_id = 'noserial'
input_file_directory  = platform_directory + '/' + folder_project + '/' + folder_raw   + '/' + folder_year + '/' + school_name + '/' + manuf_id + '/'+ class_dir + '/'
export_file_directory = platform_directory + '/' + folder_project + '/' + folder_ready + '/' + folder_year + '/' + school_name + '/' + manuf_id + '/'+ class_dir + '/'

## 31

In [71]:
school_name = 'brannfjell'
manuf_id    = 'sdanlegg'
instr_id    = 'schneider'
class_dir = '31'
serial_id = 'noserial'
input_file_directory  = platform_directory + '/' + folder_project + '/' + folder_raw   + '/' + folder_year + '/' + school_name + '/' + manuf_id + '/'+ class_dir + '/'
export_file_directory = platform_directory + '/' + folder_project + '/' + folder_ready + '/' + folder_year + '/' + school_name + '/' + manuf_id + '/'+ class_dir + '/'

## Processor

In [72]:
folder_path1 = input_file_directory # replace with the folder path
csv_files1 = [f for f in os.listdir(folder_path1) if f.endswith('.csv')] # get list of csv files

dfs1 = [] # list to store dataframes

for file in csv_files1:
    file_path = os.path.join(folder_path1, file) # get full path of csv file
    df = pd.read_csv(file_path) # read csv file into a dataframe
    dfs1.append(df) # append dataframe to list

In [73]:
DF1 = pd.concat(dfs1, ignore_index=False)
DF1['Timestamp'] = pd.to_datetime(DF1['Timestamp'], format = '%d.%m.%Y %H:%M:%S')
DF1 = DF1.sort_values(by=['Timestamp'], ignore_index=True)
DF1.columns = [ datetime_name ,temp_data_name, temp_set_name, co2_data_name ]
DF1 = DF1.set_index(['datetime']).replace(to_replace = ',', value='.', regex = True).replace(to_replace = '\xa0', value='', regex = True).astype(float).resample('1min').mean()
DF1[temp_set_name] = DF1[temp_set_name] .fillna(method='ffill').fillna(method='bfill')
DF1.loc[:,[co2_data_name, temp_data_name]] = DF1.loc[:,[co2_data_name, temp_data_name]] .interpolate(method='index').fillna(method= 'bfill')
DF1.reset_index(inplace=True)

# Adjust the datetime to the Oslo timezone and account for daylight saving time
#DF1['Name :'] = DF1['Name :'].dt.tz_convert(utc_timezone)
DF1[datetime_name] = DF1[datetime_name].dt.tz_localize(oslo_timezone, nonexistent='shift_forward').dt.tz_convert(utc_timezone)
DF1[datetime_name] = DF1[datetime_name].dt.tz_localize(None)
DF1[date_name]   = DF1[datetime_name].dt.strftime(date_format_show)
DF1[time_name]   = DF1[datetime_name].dt.strftime(time_format_show)
DF1.drop(columns=[datetime_name], inplace = True)

DF1 [school_col_name]  = school_name
DF1 [room_col_name]    = class_dir
DF1 [manuf_col_name]   = manuf_id
DF1 [instr_col_name]   = instr_id
DF1 [serial_col_name]  = serial_id
 #.astype(float).interpolate(method='linear').fillna(method='bfill')
cols_to_move = [school_col_name , room_col_name, date_name, time_name, manuf_col_name, instr_col_name, serial_col_name  ]
DF1         = DF1[ cols_to_move + [ col for col in DF1.columns if col not in cols_to_move ]] #.drop(columns=['Date', 'Time'])

In [74]:
DF1.head(5)

,school_id,room_id,date,time,manuf_id,instr_id,serial_id,temp_v,temp_s,co2_v
0,brannfjell,31,2023-03-08,10:30,sdanlegg,schneider,noserial,21.58,18.5,516.990000
1,brannfjell,31,2023-03-08,10:31,sdanlegg,schneider,noserial,21.58,18.5,533.706667
2,brannfjell,31,2023-03-08,10:32,sdanlegg,schneider,noserial,21.58,18.5,550.423333
3,brannfjell,31,2023-03-08,10:33,sdanlegg,schneider,noserial,21.58,18.5,567.140000
4,brannfjell,31,2023-03-08,10:34,sdanlegg,schneider,noserial,21.58,18.5,583.893333

In [75]:
#put spesific Directory and File Name.
directory_path = export_file_directory
name_time = datetime.strptime((DF1['time'].iloc[0]),'%H:%M').strftime('%H%M')
name_date = datetime.strptime((DF1['date'].iloc[0]),'%Y-%m-%d').strftime('%Y%m%d')

filename = school_name+'_'+class_dir+ '_'+ instr_id + '_'+serial_id +'_'+name_date +'_'+ name_time + '.csv'

# save dataframe to CSV file in specified directory
DF1.to_csv(directory_path + filename, index=False)

# Kuben

## 2708

## 3707

## 3708